dist: xenial
os: linux
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
jobs:
  include:
    - python: "3.7"
    - python: "3.8"
      env:
        - BUILD_DOCS=true
        - DEPLOY_PYPI=true
    - os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - BUILD_WHEEL=true
      before_install:
        - choco install python --version 3.8.0
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe
    - os: osx
      osx_image: xcode12
      language: shell
      env: BUILD_WHEEL=true
install:
  - pip3 install -e .[dev]
script:
  - pylint hgp tests
  - mypy hgp
  - |
    coverage run --source=hgp --omit="**/__main__.py" -m pytest tests && \
    coveralls
  - |
    if [[ -n "$BUILD_DOCS" ]]; then
      make -C docs doctest && \
      make -C docs linkcheck && \
      make -C docs html;
    fi
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Ljvtl2KpZc9FHlmwjdIbNX5WO4HHFnTsWd9/a3pTQY3X/+TY1ood0M2JdJKGR36tqDtwU2Nr76oZfrTbLLurkJDRG5lm2pxD7T3/8dZdxXaEWMPORbgYWSzOqt/eHjF588PFhVyXENj+0HaLjhvUOavzU1b2zXgBFY60U5ZuLO/gwzQZEDY0Dc/JtGxEoczekTW+qG49Zk/7M5wzLA+XMllThhq+qda646D9+FMu3ob3Z8szXYTgmlcNUxaHKCWzjuSaOSk2NbyBC7+0webpoyHlK2j95T2vB65qzO3wzdscZ2wJiahu5udt5MFVAVisb8bP8XLrAU0x+5pygM/nUFE6GgrXcyW1fQxGJDEOr77guNx1sBX/gQ7TBzCLl9C0++0u95M59ZT2SMdF6YZLvxH+9AjXSQx7L4NXQQDm2xxCl6OFCZmk4cdhb/KpyLwIhr8vrBv0TPv8ohEImJe9LO9n3gZ7BVJrOs1XJeQMLm+XIdFd+8ySSSxT3wggQAEnkUDZ9UF/unbcS7aRxLFBQUE9Va2UCUPTsUB02ZuLJiOSAqAAIMl+bmwZ31dTHPs3P4kLDmcg+/p5zIFhh7vlP/8XM3VFSrFQh0GShlbXBTac0lPFM9rLPgx1cXT8irSsslDlFf82Fs4H7PCYcn8+l9+AQQ4KNrb5yXvuxg72CN8="
  on:
    repo: klittlepage/hgpmatch
    tags: true
    branch: master
    condition: $DEPLOY_PYPI
  cleanup: false
  skip_existing: true
  distributions: "sdist bdist_wheel"
